/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#bec6e0",
        "surface-variant": "#d3e4fe",
        "on-primary": "#ffffff",
        "surface-bright": "#f8f9ff",
        "surface-container": "#e5eeff",
        "on-secondary-fixed": "#001e2c",
        "primary": "#000000",
        "on-secondary-container": "#004d6a",
        "on-tertiary-container": "#818486",
        "surface-container-low": "#eff4ff",
        "secondary-fixed-dim": "#7bd0ff",
        "on-surface-variant": "#45464d",
        "surface-container-high": "#dce9ff",
        "on-tertiary-fixed": "#191c1e",
        "secondary-fixed": "#c4e7ff",
        "surface-container-highest": "#d3e4fe",
        "outline-variant": "#c6c6cd",
        "on-error-container": "#93000a",
        "background": "#f8f9ff",
        "inverse-surface": "#213145",
        "on-surface": "#0b1c30",
        "primary-container": "#131b2e",
        "primary-fixed": "#dae2fd",
        "surface-dim": "#cbdbf5",
        "error-container": "#ffdad6",
        "tertiary-container": "#191c1e",
        "on-tertiary-fixed-variant": "#444749",
        "inverse-primary": "#bec6e0",
        "surface-tint": "#565e74",
        "surface": "#f8f9ff",
        "tertiary": "#000000",
        "on-primary-fixed": "#131b2e",
        "secondary": "#00668a",
        "tertiary-fixed": "#e0e3e5",
        "on-background": "#0b1c30",
        "on-primary-container": "#7c839b",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed-dim": "#c4c7c9",
        "inverse-on-surface": "#eaf1ff",
        "on-error": "#ffffff",
        "outline": "#76777d",
        "on-primary-fixed-variant": "#3f465c",
        "on-secondary-fixed-variant": "#004c69",
        "error": "#ba1a1a",
        "on-secondary": "#ffffff",
        "on-tertiary": "#ffffff",
        "secondary-container": "#40c2fd"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-mobile": "16px",
        "gutter": "24px",
        "baseline": "4px",
        "margin-desktop": "32px",
        "container-max": "1440px"
      },
      fontFamily: {
        "body-lg": ["Inter"],
        "headline-sm": ["Inter"],
        "body-md": ["Inter"],
        "headline-lg": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "body-sm": ["Inter"],
        "label-caps": ["Inter"],
        "data-mono": ["Inter"],
        "headline-md": ["Inter"]
      },
      fontSize: {
        "body-lg": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "headline-sm": ["18px", {"lineHeight": "1.4", "fontWeight": "600"}],
        "body-md": ["14px", {"lineHeight": "1.5", "fontWeight": "400"}],
        "headline-lg": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "headline-lg-mobile": ["24px", {"lineHeight": "1.2", "fontWeight": "700"}],
        "body-sm": ["13px", {"lineHeight": "1.5", "fontWeight": "400"}],
        "label-caps": ["11px", {"lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "data-mono": ["14px", {"lineHeight": "1", "fontWeight": "500"}],
        "headline-md": ["24px", {"lineHeight": "1.3", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
}
